# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

# ThymeleafProperties
spring:
  thymeleaf:
    cache: false

# DataSourceProperties
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
      username: root
      password: 596098


# MailProperties
  mail:
    host: smtp.126.com
    port: 465
    username: liuyang_1026@126.com
    password: BTKVIBQKMDEORWUZ
    protocol: smtps

# RedisProperties
  redis:
    database: 11
    host: 192.168.115.130
    port: 6379
    password: 596098

#KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      #自动提交的频率：3秒
      auto-commit-interval: 3000





# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.newcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true


# logger
#logging:
#  level:
#    com.newcoder.community: debug
#  file:
#    name: d:/linux/data/nowcoder/community.log


community:
  path:
    domain: http://localhost:8080
    #自己定义的文件上传地址
    upload: d:/linux/img





